add-search
MariaFantasy/java-filmorate pull request #11
Opened 2024-12-05 23:30 UTC by allon21

Добавлено поиск по названию фильмов и по режиссёру

2024-12-06 05:05 UTC, Sergei-Lukashenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    "GROUP_CONCAT(g.genre_id) AS genre_ids, GROUP_CONCAT(g.name) AS genre_names " +
Интересная SQL-функция GROUP_CONCAT, не знал про нее, почитал

2024-12-06 05:06 UTC, Sergei-Lukashenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    "GROUP BY f.film_id, r.rating_id, d.director_id";
Некритично, но если большие SQL-запросы записывать в многострочных литералах (в тройных кавычках), то может быть проще взять текст  SQL с помощью copy-paste для проверки гле-нибудь в DBeaver

2024-12-06 05:10 UTC, Sergei-Lukashenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String directorNames = rs.getString("director_name");
В SQL-запросе поля director_id и director_name в единственном числе, а здесь переменные directorIds и directorNames во множественном, как будто это списки через запятую. Здесь все верно?

2024-12-06 08:50 UTC, MariaFantasy requested changes
Поправь, пожалуйста, с loadDirectors и loadGenres, а то ревьюер нам это не пропустит

2024-12-06 08:50 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            resultFilms.addAll(filmStorage.searchFilmsByDirector(query));
А сортировка по популярности? Если искать по ключевому слову одновременно по режиссеру и названию, может не соблюдаться последовательность

2024-12-06 08:50 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    "GROUP_CONCAT(g.genre_id) AS genre_ids, GROUP_CONCAT(g.name) AS genre_names " +
Мой ревьювер был против SQL запросов со связкой многие-ко-многим
Для этого есть функция loadGenres, используй ее, пожалуйста

2024-12-06 08:50 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Film mapFilm(ResultSet rs) throws SQLException {
У меня есть уже реализованный маппер, лучше вносить изменения туда

2024-12-06 08:50 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (directorNames != null) {
Аналогично моему комментарию выше, в сервисах специально есть функция loadDirectors и loadGenres

2024-12-07 13:48 UTC, MariaFantasy requested changes

2024-12-07 13:48 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                         LEFT JOIN film_director AS fd ON f.film_id = fd.film_id
film_director и director тут уже не нужен, да и строчки дублировать будет
+ в селекте убери поле

2024-12-07 13:48 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                         LEFT JOIN film_director AS fd ON f.film_id = fd.film_id
Аналогично в запросе ниже

2024-12-08 10:38 UTC, MariaFantasy approved these changes

2024-12-08 11:52 UTC, Sergei-Lukashenko approved these changes

2024-12-08 19:51 UTC, merged