add-recommendations
MariaFantasy/java-filmorate pull request #12
Opened 2024-12-06 06:10 UTC by kpak292

Описание задачи
Реализовать простую рекомендательную систему для фильмов. Примерный алгоритм выглядит следующим образом:

Найти пользователей с максимальным количеством пересечения по лайкам.
Определить фильмы, которые один пролайкал, а другой нет.
Рекомендовать фильмы, которым поставил лайк пользователь с похожими вкусами, а тот, для кого составляется рекомендация, ещё не поставил.
Более подробно подобный алгоритм описан в этой [статье](https://www.baeldung.com/java-collaborative-filtering-recommendations).

API
GET /users/{id}/recommendations

Возвращает рекомендации по фильмам для просмотра.

2024-12-06 15:52 UTC, Sergei-Lukashenko approved these changes

2024-12-07 11:16 UTC, MariaFantasy requested changes
Точно нужно убрать обращение из UserService в FilmStorage

2024-12-07 11:16 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final FilmStorage filmStorage;
Ревьюер мне ранее писал, что Storage и Controller-классы должны общаться только со своим сервисом, если нужно что-то из другой области, то нужно обращаться к соответствующему сервису

2024-12-07 11:16 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (BadSqlGrammarException e) {
Как будто бы эта ошибка должна отрабатываться на этапе разработки, зачем этот чек?

2024-12-07 14:05 UTC, kpak292 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (BadSqlGrammarException e) {
Да, это я дебажил, забыл убрать, спасибо

2024-12-07 14:09 UTC, kpak292 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final FilmStorage filmStorage;
Поправил, спасибо

2024-12-08 10:40 UTC, MariaFantasy approved these changes

2024-12-08 11:59 UTC, merged