Реализация нового функционала
MariaFantasy/java-filmorate pull request #15
Opened 2024-12-09 04:56 UTC by MariaFantasy

Новые фичи:
1. Функциональность «Отзывы».
2. Функциональность «Поиск».
3. Функциональность «Общие фильмы».
4. Функциональность «Рекомендации».
5. Функциональность «Лента событий».
6. Функциональность «Популярные фильмы», которая предусматривает вывод самых любимых у зрителей фильмов по жанрам и годам.
7. Функциональность «Фильмы по режиссёрам», которая предполагает добавление к фильму информации о его режиссёре.
8. Функциональность «Удаление фильмов и пользователей», которая предусматривает удаление фильма или пользователя по идентификатору.

2024-12-10 15:57 UTC, YazykovMikhail requested changes

2024-12-10 15:57 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("Пришел GET запрос /reviews");
Стоит логировать входящие данные, иначе как потом опнять что пришло в запросе

2024-12-10 15:57 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (Arrays.asList(searchFields).contains("title")) {
Стоит вынести в константы, у всего должно быть название, например

2024-12-10 15:57 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +    private static final String FIND_ALL_QUERY = "SELECT director_id, name FROM director ORDER BY director_id";
Статические переменные обьяввлюяься первыми в классе - по код стайлу

2024-12-10 15:57 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +    private static final String FIND_ALL_QUERY = "SELECT director_id, name FROM director ORDER BY director_id";
Поправьте во всем коде

2024-12-10 15:57 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private static final String RECOMMENDATION_LIST_QUERY = """
Попробуй вот такой запрос, как будто будет получше, если я нчиего не пропустил:

```
SELECT
    f.film_id,
    f.name,
    f.description,
    f.release_date,
    f.duration,
    f.rating_id,
    r.name AS rating_name
FROM film AS f
LEFT JOIN rating AS r ON f.rating_id = r.rating_id
WHERE f.film_id IN (
    SELECT fl.film_id
    FROM film_like AS fl
    INNER JOIN (
        SELECT ul.user_id, COUNT(ul.film_id) AS balls
        FROM film_like AS ul
        WHERE ul.film_id IN (
            SELECT film_id
            FROM film_like
            WHERE user_id =?
        )
        GROUP BY ul.user_id
    ) AS fb ON fl.user_id = fb.user_id
    WHERE fl.user_id!=?
    GROUP BY fl.film_id
    ORDER BY SUM(fb.balls) DESC
);
```

2024-12-10 18:38 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("Пришел GET запрос /reviews");
Добавили и проверили другие методы на предмет пропуска логирования тела или параметров запроса

2024-12-10 18:38 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (Arrays.asList(searchFields).contains("title")) {
Вынесли статистеческие константы для title и director - SEARCH_BY_TITLE и SEARCH_BY_DIRECTOR соответственно

2024-12-10 18:40 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +    private static final String FIND_ALL_QUERY = "SELECT director_id, name FROM director ORDER BY director_id";
Проверили все классы на подобные проблемы и перенесли наверх, где нашли

2024-12-10 18:43 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private static final String RECOMMENDATION_LIST_QUERY = """
Есть проблема с вычисткой из результирующего списка фильмов, которые и так у исходного юзера были в лайках
Перенесла последнее сравнение на неравенство юзера текущему в блок HAVING для вычисления флага, что фильм есть у данного юзера

2024-12-11 16:46 UTC, YazykovMikhail approved these changes

2024-12-11 17:46 UTC, merged