Добавление базы данных
MariaFantasy/java-filmorate pull request #4
Opened 2024-11-23 09:20 UTC by MariaFantasy

Добавлен новый функционал:
- Добавление в друзья
- Жанры и рейтинги фильмов

Кроме того:
- Данные перенесены в базу данных 
- Добавлены классы-репозитории для работы с базой данных
- Добавлены сервисы жанров, рейтингов и дружбы
- Добавлены контроллеры для обработки запросов к жанрам и рейтингам

2024-11-24 10:59 UTC, YazykovMikhail requested changes

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        if (genre == null) {
Этот код лучше вынести в сервис

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final MpaService mpaService;
Репозитории не должны зависить от других сервисов/репозиторий.
Они общаются только с БД и все

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film create(Film film) {
Вот как может выглядить метод сохранения, с учетом что м не ходим в другие сервиса
```

	@Override
	public void save(Film film) {
		String sqlQuery = "insert into FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATE, MPA_ID) values (?, ?, ?, ?, ?, ?)";

		KeyHolder keyHolder = new GeneratedKeyHolder();
		jdbcTemplate.update(connection -> {
			PreparedStatement stmt = connection.prepareStatement(sqlQuery, new String[]{"FILM_ID"});
			stmt.setString(1, film.getName());
			stmt.setString(2, film.getDescription());
			stmt.setDate(3, Date.valueOf(film.getReleaseDate()));
			stmt.setLong(4, film.getDuration());
			stmt.setLong(5, film.getRate());
			stmt.setLong(6, film.getMpa().getId());
			return stmt;
		}, keyHolder);
		film.setId(keyHolder.getKey().longValue());

		saveGenres(film);
	}
```

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film create(Film film) {
```
	private void saveGenres(Film film) {
		final Long filmId = film.getId();
		jdbcTemplate.update("delete from FILM_GENRES where FILM_ID = ?", filmId);
		final Set<Genre> genres = film.getGenres();
		if (genres == null || genres.isEmpty()) {
			return;
		}
		final ArrayList<Genre> genreList = new ArrayList<>(genres);
		jdbcTemplate.batchUpdate(
				"insert into FILM_GENRES (FILM_ID, GENRE_ID) values (?, ?)",
				new BatchPreparedStatementSetter() {
					public void setValues(PreparedStatement ps, int i) throws SQLException {
						ps.setLong(1, filmId);
						ps.setLong(2, genreList.get(i).getId());
					}

					public int getBatchSize() {
						return genreList.size();
					}
				});
	}
```

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Collection<Film> findAll() {
Свзяь фильмов и жанров многие ко многим, делать join многих ко многим не стоит, хоть ты и применяешь дистинкт, это достаточно обьемный запрос

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Collection<Film> findAll() {
А вот МПА стоит получть сразу в запросе
```

	@Override
	public Film get(long id) {
		final String sqlQuery = "select * from FILMS f, MPA m where f.MPA_ID = m.MPA_ID AND FILM_ID = ?";
		final List<Film> films = jdbcTemplate.query(sqlQuery, DbFilmStorage::makeFilm, id);
		if (films.size() != 1) {
			throw new DataNotFoundException("film id=" + id);
		}
		return films.get(0);
	}
```
Что делать с жанрами покажу в сервисе

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Collection<Film> findAll() {
public List<Film> getAll() {
		final List<Film> films = super.getAll();
		genreStorage.load(films);
		return films;
	}

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Collection<Film> findAll() {
А метод load для загрузки жанров будет выглдяить вот так:
```

	@Override
	public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(Film::getId).toArray());
	}

	static Genre makeGenre(ResultSet rs, int rowNum) throws SQLException {
		return new Genre(
				rs.getLong("genre_id"),
				rs.getString("name"));
	}
```

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          return filmStorage.findById(filmId);
Анологично для методе гет, можно использовать тот же лоад метод:
```

	public Film get(long id) {
		final Film film = super.get(id);
		genreStorage.load(Collections.singletonList(film));
		return film;
	}
```

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        } catch (EmptyResultDataAccessException ignored) {
Не стоит возвращать null, пусть возвращется исключение - исключение значит обьект не надйен.
null - не понятно, из за null может быть множетсво ошибок.

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            return null;
Можно просто выбрасывать свое исключение
`throw new DataNotFoundException("user id=" + id);`
что бы не показываать структуру кода

2024-11-24 10:59 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            return null;
Попарвь везде

2024-11-24 19:34 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        if (genre == null) {
По сути ошибка уже всплывает на уровне Storage

2024-11-24 19:35 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        if (genre == null) {
Поэтому убрала в целом

2024-11-24 23:03 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film create(Film film) {
Так не обрабатывается ситуация с невалидными жанрами (которых нет в таблице с жанрами)
Попробую вынести проверку в сервис, но суть не меняется

2024-11-24 23:18 UTC, MariaFantasy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film create(Film film) {
Собственно сервис я использовала только для проверки

2024-11-25 14:29 UTC, YazykovMikhail approved these changes

2024-12-03 08:27 UTC, merged